TERMUX_PKG_HOMEPAGE=https://www.netlib.org/blas/
TERMUX_PKG_DESCRIPTION="Basic Linear Algebra Subprograms"
TERMUX_PKG_VERSION="3.7.0"
TERMUX_PKG_SHA256=55415f901bfc9afc19d7bd7cb246a559a748fc737353125fcce4c40c3dee1d86
TERMUX_PKG_SRCURL=http://www.netlib.org/blas/blas-${TERMUX_PKG_VERSION}.tgz
TERMUX_PKG_FOLDERNAME="BLAS-${TERMUX_PKG_VERSION}"
TERMUX_PKG_BUILD_IN_SRC=yes
TERMUX_PKG_KEEP_STATIC_LIBRARIES=yes

termux_step_make_install () {
    cp ${TERMUX_PKG_SRCDIR}/blas_LINUX.a ${TERMUX_PREFIX}/lib/libblas.a
}
